### ISSUE TITLE
should all dependencies be devdependencies?

### ISSUE THREAD

**Issue by UziTech** [atom-community/atom-ide-template#26]
Should all dependencies be devdependencies? Since rollup bundles them anyway is there a reason to download them when installing the package?

**Comment by aminya** [comment]
Based on my experience this is not straight forward and it requires a lot of workarounds. Plus this makes keeping track of the actual dependencies harder.

https://github.com/thgh/rollup-plugin-css-only/pull/19#issuecomment-637423260
