### ISSUE TITLE
using pnpm causes problems

### ISSUE THREAD

**Issue by UziTech** [atom-community/atom-ide-template#27]
It seems counter productive to use pnpm. There have been quite a few times I have run into issues because atom doesn't use pnpm so something might work in development but not in production because of the differences between pnpm and npm.

I understand the benefits of pnpm but since atom uses npm I think we should also use npm on development.

**Comment by aminya** [comment]
We test the packages using `npm`, and so we are sure that it works. Personally, I have not found any issue that is not solvable.

**Comment by UziTech** [comment]
> I have not found any issue that is not solvable.

yet still extra work to solve them.

Can you fix the dependency update in [terminal](https://github.com/atom-ide-community/terminal/runs/1088658329?check_suite_focus=true)?

**Comment by aminya** [comment]
The pnpm lock file was not in sync with package.json. You should use `pnpm install` whenever you want to bump a dependency so the lock file gets updated.

**Comment by UziTech** [comment]
i think atom-ide-community/terminal is a case where pnpm doesn't make sense. it doesn't even work to use `pnpm install && apm rebuild` to install the dependencies so the pnpm lock file seems useless.

**Comment by aminya** [comment]
I have made an issue for the terminal. Let's see what happens

https://github.com/pnpm/pnpm/issues/2883

**Comment by aminya** [comment]
We should use `npm` in the terminal because of the way it builds the native module. Based on what was discussed in https://github.com/pnpm/pnpm/issues/2883#issuecomment-696671849 currently, there is no way to copy the dependencies to node_modules using `pnpm`. So we need to use `npm` for the packages that fail to build for some reason.
